### ISSUE TITLE
Error: `cannot execute: required file not found`

### ISSUE THREAD

**Issue by thenbe** [sgb-io/fta#29]
```
/bin/sh: line 1: /home/nbe/.local/share/pnpm/global/5/.pnpm/fta-cli@0.1.10/node_modules/fta-cli/binaries/x86_64-unknown-linux-gnu/fta: cannot execute: required file not found                                                                
```

[![asciicast](https://asciinema.org/a/588329.svg)](https://asciinema.org/a/588329)

Might the issue might be related to the `/bin/sh` shebang?  `nixOS` often struggles with this form and prefers the [more portable alternative](https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang/10383546#10383546).

```diff
- #!/bin/sh
+ #!/usr/bin/env bash
```

**Comment by sgb-io** [comment]
Hi @thenbe, thanks for reporting this. I'm not sure what the problem is yet. I have been testing primarily on Ubuntu and not other distros, hence `fta` may be broken on nixOS.

The npm package actually uses [`#!/usr/bin/env node`](https://github.com/sgb-io/fta/blob/main/packages/fta/index.js#L1) and the output to me suggests that the node script is being called just fine (it attemps to launch the child process, visible in the stacktrace).

However, it seems like the node process cannot see or execute the `fta` binary. I wonder if manually `chmod +x`ing the binary changes anything?

**Comment by thenbe** [comment]
> manually chmod +xing the binary

No luck. Still getting `no such file or directory` as seen in the gif above.

---

After some digging around I stumbled upon [this](https://github.com/emk/rust-musl-builder/issues/77#issuecomment-512764444) similar issue. Now, I'm not familiar with these libraries and honestly have no idea if this is even applicable for our scenario, but I'll leave it here perhaps it might come in handy in the future.

```bash
$ ldd fta

linux-vdso.so.1 (0x00007ffc1e48d000)
libgcc_s.so.1 => /nix/store/0fvh2p4irz0lw0cpy2ll1rf2hbhbym3g-xgcc-12.2.0-libgcc/lib/libgcc_s.so.1 (0x00007f35db50c000)
libpthread.so.0 => /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib/libpthread.so.0 (0x00007f35db507000)
libm.so.6 => /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib/libm.so.6 (0x00007f35daf20000)
libdl.so.2 => /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib/libdl.so.2 (0x00007f35db502000)
libc.so.6 => /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib/libc.so.6 (0x00007f35dad3a000)
/lib64/ld-linux-x86-64.so.2 => /nix/store/yaz7pyf0ah88g2v505l38n0f3wg2vzdj-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007f35db52f000)
```

**Comment by sgb-io** [comment]
It seems like this is somewhat specific to `nixOS`. I am not very familiar with that OS.

https://nixos.wiki/wiki/Packaging/Binaries states:
> Downloading and attempting to run a binary on NixOS will almost never work

My assumption is that the static linking isn't working because the binary is making assumptions about how to link those dependencies - which is a problem on nixOS in particular.

A possible solution is a nixOS-specific binary.

I'll leave this issue open for any suggestions.

**Comment by sgb-io** [comment]
Hi @thenbe fta has been updated to distribute musl binaries now, which should mean that the C stdlib is statically linked. It should mean that the binaries are more widely compatible.

It's worth seeing if this issue still occurs - `npx fta-cli path/to/code`

**Comment by thenbe** [comment]
Yup I'm able to run it now. Thank you.
