### ISSUE TITLE
Consider adding an option to ignore comments

### ISSUE THREAD

**Issue by MohnJcAfee** [sgb-io/fta#45]
pretty much what the title says :)

Currently comments do affect the fta score (at least for js-only projects, can't speak for typescript). 
So if you've got to/want to write JSDoc comments, due to their "verbosity" they push the score higher without (at least in my opinion) actually reducing readablity/complexity.

Therefore it would be nice if we had an option to ignore comments (maybe prune them with swc minify?).

Thanks in advance!

**Comment by sgb-io** [comment]
I will look into this! You're right that the scores should not be going higher because of JSDoc comments.

**Comment by sgb-io** [comment]
I think the crux of this issue is that number of lines are used as part of the overall score calculation. The fix is to exclude comments from this number, because as a rule of thumb, they improve the maintainability of code as opposed to increasing complexity (the same cannot be said for adding more lines of code).

[This piece of code](https://github.com/sgb-io/fta/blob/main/crates/fta/src/parse/mod.rs#L10) would need to become smarter.

**Comment by sgb-io** [comment]
This is solved via new options and defaults in #47 (thanks @bencollins54), just needs some tidy up

**Comment by sgb-io** [comment]
This is resolved in v1.0.0
